### PR TITLE
Fix #515

### LINKED ISSUE #515: Sort out google indexing

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Is there anything other than the ban icon that's misleading enough to fix?

### CODE REVIEW

**Comment by YaManicKill** [comment]
Oh awesome.

The other thing was that sometimes we show the privacy policy, so probably just pull that modal down to the bottom of the page?

**Comment by YaManicKill** [comment]
I'd like to figure out why the others aren't working before we merge this in, because if we get rid of the privacy policy, we still have other things that'll show up instead.

I thought it was a controller issue, but they are still in the userCtrl when you put them below the footer. Very weird :-\ I'll take a look later.

**Comment by YaManicKill** [comment]
Alright, I'm not going to end up fixing that anytime soon. Rebase and I'll merge. Will do it at some point, but it's better not to be misleading with the ban.

**Comment by not-an-aardvark** [comment]
Rebased.

**Pull request merged**
