### PR TITLE
Banlist hover

### LINKED ISSUE #582: Built-in banlist hover feature
Since the formatting to do the hover stuff is weird, ideally we'd be able to do that automatically too. I'm envisioning something like this:

https://i.imgur.com/u0EgkF6.png

The formatting is this:

` [YYY](#b "XXX (hover)")`

Where XXX is the label (yes/no/some), and YYY is the text that appears after hovering.

### PR DESCRIPTION
**Pull request by robdy**
Fixes #582. Changed 'Retrading allowed' to inline radio and added new field:
image

Result:
image

### CODE REVIEW

**Comment by Kirzi** [comment]
I think ideally, the "hover note" box is hidden unless "some" is selected, since it turns out that it's not really needed much. But I'm fine with this as is. Thanks for working on it.

**Comment by robdy** [comment]
I initially left it visible as there was one entry with `Yes (hover)` but perhaps you're right that it won't probably be used. Will fix it a bit later.

**Comment by robdy** [comment]
Ok, all done (hiding + check if empty).

**Comment by Kirzi** [comment]
Looks good to me, thanks. (tested to check the look/behavior but didn't actually ban anyone)

**Comment by McInkay** [comment]
Soon never came. Closing as this will also be superceded.

**Pull request closed without merging**
